### PR TITLE
bump fips timeout to 5 hours

### PR DESCRIPTION
**Pull request by trevor-vaughan**

### CODE REVIEW

**Comment by trevor-vaughan** [comment]
Unable to reproduce `stunnel` failure locally.

**Comment by op-ct** [comment]
I still think 5h is a long time, considering the number of repos vs beaker runners that we have.

**Comment by trevor-vaughan** [comment]
@op-ct Honeslty, I have no idea. I kept bumping it up since it would pass locally and fail on the runners with a timeout. I feel like there's something else going on here and it's probably not a good idea to set it that high.

**Comment by trevor-vaughan** [comment]
I'm going to close this and we can try to address it again later on.

**Pull request closed without merging**
