### PR TITLE
(SIMP-4637) Use stunnel systemd service deps

### PR DESCRIPTION
**Pull request by jeefberkey**
On systemd systems, the stunnel service is now a dependency of the NFS
servers and mounts managed by this module.

SIMP-4637 #close

### CODE REVIEW

**Comment by jeefberkey** [comment]
Do not merge until the stunnel change mentioned in the fixtures.yaml is removed (https://github.com/simp/pupmod-simp-stunnel/pull/55)

**Comment by jeefberkey** [comment]
:clock3: https://gitlab.com/simp/pupmod-simp-nfs/pipelines/20042515

**Comment by jeefberkey** [comment]
:heavy_check_mark: https://gitlab.com/simp/pupmod-simp-nfs/pipelines/20216457

**Comment by jeefberkey** [comment]
:clock4: simp_nfs integration running at https://gitlab.com/simp/pupmod-simp-simp_nfs/pipelines/20222874

**Comment by jeefberkey** [comment]
I'm seeing an issue where puppet runs fail because of the new dependencies for the stunnel service on the server. In the simp_nfs tests linked above, the error looks like this:

```
Error: Could not enable stunnel_managed_by_puppet_nfs: 
Error: /Stage[main]/Nfs::Server::Stunnel/Stunnel::Instance[nfs]/Service[stunnel_managed_by_puppet_nfs]/ensure: change from stopped to running failed: Could not enable stunnel_managed_by_puppet_nfs: 
```

It's always fine the second run, it just seems to be a small timeout thing. Maybe I can set that in the stunnel service...

Here's how you can replicate it in the acceptance tests:
```
systemctl disable rpc-statd nfs-mountd nfs-rquotad nfs-server rpcbind.socket nfs-idmapd stunnel_managed_by_puppet_nfs.service --now
```

**Comment by jeefberkey** [comment]
:heavy_check_mark: https://gitlab.com/simp/pupmod-simp-nfs/pipelines/20396310

**Comment by trevor-vaughan** [comment]
The code looks fine and I haven't been able to get it to fail during my testing. Seems to work across the board in GitLab now. The last FIPS mode error was just a fluke of the run.

**Comment by jeefberkey** [comment]
:heavy_check_mark: nfs https://gitlab.com/simp/pupmod-simp-nfs/pipelines/20458998
:heavy_check_mark: simp_nfs https://gitlab.com/simp/pupmod-simp-simp_nfs/pipelines/20459249

**Pull request merged**
